Nutrition APIs addition to iOS
metaflowltd/flutter_health_fit pull request #19
Opened 2021-05-23 12:30 UTC by rtokun

2021-05-23 14:07 UTC, avi-mastov reviewed
Somehow it because 6 data points 😄
Anyway, please extract the common code in SwiftFlutterHealthFitPlugin.

2021-05-23 14:07 UTC, avi-mastov commented on ios/Classes/HealthkitReader.swift
> +                                            print("Amount of \(value): \(sampleType), since: \(queryResult.startDate) until: \(queryResult.endDate)")
```suggestion
                                            print("Amount of \(sampleType): \(value), since: \(queryResult.startDate) until: \(queryResult.endDate)")
```

2021-05-23 14:07 UTC, avi-mastov commented on ios/Classes/SwiftFlutterHealthFitPlugin.swift
> +        }
There is so much common code. I'm sure you can extract a method.

2021-05-23 14:35 UTC, TSurkis requested changes

2021-05-23 14:35 UTC, TSurkis commented on ios/Classes/SwiftFlutterHealthFitPlugin.swift
> +        else if call.method == "getSugarConsumed" {
Can't we create a method for this? There is a lot of copy paste in here.
I see that the only variables here are: `unit`, `logString`, `sampleType`

2021-05-23 14:35 UTC, TSurkis commented on lib/flutter_health_fit.dart
> +  Future<int> getEnergyConsumed(int start, int end) async {
This too can be broken down to a simple method that can be reused:
You can use a different name. This one isn't that good :)

```
  Future<int> invokeiOSMethodOnly(String methodName, int start, int end) async {
    if(!Platform.isIOS) return null;

    return await _channel.invokeMethod(methodName, {"start": start, "end": end});
  }
```

2021-05-24 05:34 UTC, rtokun commented on lib/flutter_health_fit.dart
> +  Future<int> getEnergyConsumed(int start, int end) async {
We already have that similar functionality inside the plugins. Some of the APIs are for one platform only, but the consumer shouldn't bother about it.
In the near future, we will add support for Android as well and it will be seamless to the client.
I will add comments to the methods though.

2021-05-24 05:46 UTC, TSurkis approved these changes

2021-05-24 05:46 UTC, TSurkis commented on ios/Classes/SwiftFlutterHealthFitPlugin.swift
> +        else if isCallNutritionBySample(call) {
Beautiful 🌹

2021-05-24 06:14 UTC, avi-mastov approved these changes
👏

2021-05-24 06:14 UTC, avi-mastov commented on ios/Classes/SwiftFlutterHealthFitPlugin.swift
> +            || call.method == "getProteinConsumed"
In swift you can use a switch statement on strings too. Not critical.

2021-05-24 06:15 UTC, merged