LMN-4361 | Collect sourceporvider for weight
metaflowltd/flutter_health_fit pull request #53
Opened 2022-02-13 17:08 UTC by NimGit

Collect sourceporvider for weight

https://metaflow.atlassian.net/browse/LMN-4361

2022-02-13 17:30 UTC, rtokun requested changes

2022-02-13 17:30 UTC, rtokun commented on android/src/main/kotlin/com/metaflow/flutterhealthfit/FlutterHealthFitPlugin.kt
> +class DataPointValue(
Why not using data class?

2022-02-13 17:30 UTC, rtokun commented on lib/flutter_health_fit.dart
> +      final status = await _channel.invokeMethod("isAuthorized");
1. Please catch only specific 2 errors that relate to the background and lack of the HealthKIt.
2. Other errors you should propagate up to consumer, otherwise you swallow all potential errors and return false results.
3. In the case you catch errors here, please print the errors, otherwise we will not understand how many these errors we have.

2022-02-13 20:20 UTC, NimGit commented on android/src/main/kotlin/com/metaflow/flutterhealthfit/FlutterHealthFitPlugin.kt
> +class DataPointValue(
Not sure what you mean by "data class"
I want DataPoint to return a known structure, not each returning something else. Therefore, I created this class. I want us to use it when we refactor other data points.

2022-02-15 18:37 UTC, rtokun requested changes

2022-02-15 18:37 UTC, rtokun commented on lib/flutter_health_fit.dart
> +abstract class HealthFitAbstractLog {
No need to mention class type in the class name. You can change it to `HealthFitLog`

2022-02-16 06:58 UTC, merged