LMN-4407 | Collect Energy Consumed from Google Fit
metaflowltd/flutter_health_fit pull request #56
Opened 2022-02-21 10:12 UTC by NimGit

Collect Energy Consumed from Google Fit

https://metaflow.atlassian.net/browse/LMN-4407

2022-02-21 15:35 UTC, rtokun requested changes

2022-02-21 15:35 UTC, rtokun commented on android/src/main/kotlin/com/metaflow/flutterhealthfit/DataPointValue.kt
> +    constructor(dateInMillis: Long, value: Float, units: LumenUnit, sourceApp: String?) : this(
Please remove the constructor

2022-02-21 15:35 UTC, rtokun commented on android/src/main/kotlin/com/metaflow/flutterhealthfit/NutritionReader.kt
> +        fun getNutritionType(): DataType {
Prettier to move to const value

2022-02-21 15:35 UTC, rtokun commented on android/src/main/kotlin/com/metaflow/flutterhealthfit/NutritionReader.kt
> +        fun authorizedNutritionOptions(): FitnessOptions {
Const value

2022-02-21 15:35 UTC, rtokun commented on android/src/main/kotlin/com/metaflow/flutterhealthfit/NutritionReader.kt
> +                    val value = dataPoint.getValue(nutritionField)?.getKeyValue("calories")
If you are not using the NUTRIENT_CALORIES value, please create one in the companion object.

2022-02-21 15:35 UTC, rtokun commented on android/src/main/kotlin/com/metaflow/flutterhealthfit/NutritionReader.kt
> +                        sourceApp = "Aggregated",
Same

2022-02-21 15:35 UTC, rtokun commented on ios/Classes/HealthkitReader.swift
> +                                                    sourceApp: "Aggregated",
Constant

2022-02-21 15:35 UTC, rtokun commented on ios/Classes/SwiftFlutterHealthFitPlugin.swift
> +            getNutritionSampleInInterval(call: call, result: result)
Remove redundancy

2022-02-21 15:48 UTC, NimGit commented on android/src/main/kotlin/com/metaflow/flutterhealthfit/NutritionReader.kt
> +        fun getNutritionType(): DataType {
keeping the constructor because I want to create this object without setting the optional param additionalInfo to null

2022-02-21 15:54 UTC, NimGit commented on android/src/main/kotlin/com/metaflow/flutterhealthfit/NutritionReader.kt
> +        fun authorizedNutritionOptions(): FitnessOptions {
done

2022-02-21 15:55 UTC, NimGit commented on android/src/main/kotlin/com/metaflow/flutterhealthfit/NutritionReader.kt
> +                    val value = dataPoint.getValue(nutritionField)?.getKeyValue("calories")
done

2022-02-21 15:57 UTC, NimGit commented on android/src/main/kotlin/com/metaflow/flutterhealthfit/NutritionReader.kt
> +                        sourceApp = "Aggregated",
done

2022-02-21 15:58 UTC, NimGit commented on ios/Classes/HealthkitReader.swift
> +                                                    sourceApp: "Aggregated",
done

2022-02-22 06:47 UTC, NimGit commented on ios/Classes/SwiftFlutterHealthFitPlugin.swift
> +            getNutritionSampleInInterval(call: call, result: result)
done

2022-02-22 07:10 UTC, merged